
const seeds=[
    {id:7,
        name: 'Bengal Gram', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVCrNSBHh7FTtQU1Dome-J1aSffhl--2JZxg&usqp=CAU', 
        rating:"4/5",
        price:"150.00",
        description:"Bengal gram is widely appreciated as health food. It is a protein-rich supplement to cereal-based diets, especially to the poor in developing countries, where people are vegetarians or cannot afford animal protein. The pulse proteins are rich in lysine and have low sulfur containing amino acids.",
        category:'Grocery Seeds'
    } ,
    {id:8,
        name: 'Green Gram', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMBMF1qFiRdd74TloDvty6q239ZaQ0kPDxyg&usqp=CAU', 
        rating:"4/5",
        price:"160.00",
        description:"Green gram is a protein rich staple food. It contains about 25 percent protein, which is almost three times that of cereals. It supplies protein requirement of vegetarian population of the country. It is consumed in the form of split pulse as well as whole pulse, which is an essential supplement of cereal based diet.",
        category:'Grocery Seeds'
    } ,
    {id:9,
        name: 'Red Gram', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTshbXd2whQsK0fjywIICa9rhrJO4AQpoTz3ZO4yiUIHLtKPUGFuD1Rl2FtUvNZYtuU7a4&usqp=CAU', 
        rating:"3.5/5",
        price:"150.00",
        description:"Red gram is an important pulse crop in India. It is also known as Pigeonpea, Arhar. and Tur. Red gram is mainly cultivated and consumed in developing countries of the world.",
        category:'Grocery Seeds'
    } ,
    {id:16,
        name: 'Black Gram', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2Ih2fYFHPFlEtDH022Jf8KX7IWNlRVQizQA&usqp=CAU', 
        rating:"4/5",
        price:"180.00",
        description:"Black gram (Vigna mungo (L.) Hepper) is an erect, fast-growing annual, herbaceous legume reaching 30-100 cm in height. It has a well-developed taproot and its stems are diffusely branched from the base. Occasionally it has a twining habit and it is generally pubescent",
        category:'Grocery Seeds'
    } ,
    {id:17,
        name: 'Ground Nuts', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSM4VAt6v-w-mwV0bOWAgnbzqqG1EY4oJEWQ&usqp=CAU', 
        rating:"3.5/5",
        price:"160.00",
        description:"Peanut or groundnut (Arachis hypogaea), is a species in the legume or bean family. The peanut was probably first domesticated and cultivated in the valleys of Paraguay. It is an annual herbaceous plant growing 30 to 50 cm (1.0 to 1.6 ft) tall.",
        category:'Grocery Seeds'
    } ,
    {id:18,
        name: 'Millet', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfF_s6omVyj863MZTNFNs4tGqigseSa4_-Sw&usqp=CAU', 
        rating:"4/5",
        price:"100.00",
        description:"They are small-seeded grasses belonging to the botanical family Poaceae. They constitute an important source of food and fodder for millions of resource-poor farmers and play a vital role in ecological and economic security of India. These millets are also known as coarse cereals or cereals of the poor.",
        category:'Grocery Seeds'
    } ,
    {id:25,
        name: 'Maize', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqfrV1QkFQAElaYXkx6l8DAguD_7JMAiDk-g&usqp=CAU', 
        rating:"3.5/5",
        price:"100.00",
        description:"Maize is a cultivated grass that usually reaches around 3m in height. The stems have dark green and shiny leaves that grow alternately along either side. At the top of the stem, numerous male flowers are arranged in a complex structure resembling tassels, and release pollen when blown by the wind.",
        category:'Grocery Seeds'
    } ,
    {id:26,
        name: 'Kidney Beans', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPfOiEHhAv2VMR55ccB5M_Elu66LXrxUqUUg&usqp=CAU', 
        rating:"4/5",
        price:"150.00",
        description:"The kidney bean is a variety of the common bean (P. vulgaris), so named because of its kidney-like shape and its colour. The optimum moisture range is 12–14%. The colour of kidney beans ranges all the way from very light red to very dark, almost purple.",
        category:'Grocery Seeds'
    } ,
    {id:27,
        name: 'Barley', 
        cover:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ872JKC5zorbXM4B3DlvAHtdgUm0a6hEpvIA&usqp=CAU', 
        rating:"4/5",
        price:"60.00",
        description:"Barley, Hordeum vulgare, is an edible annual grass in the family Poaceae grown as a cereal grain crop. It is a tall grass with a hairy stem that stands erect and produces spikelets at the head. The nodes and internodes make up the stem. The internodes are hollow, as opposed to the solid internodes.",
        category:'Grocery Seeds'
    } ,
]

export default seeds;